### ISSUE TITLE
Update extension in Chrome Web Store

### ISSUE THREAD

**Issue by whalehub** [pd4d10/http-indicator#6]
The latest version of this extension is v0.0.4 but only v0.0.3 is available in the Chrome Web Store.

**Comment by whalehub** [comment]
@pd4d10 Any input on this?

**Comment by pd4d10** [comment]
Hi, @whalehub Thanks for you report!

The only difference is this PR: https://github.com/pd4d10/http-indicator/pull/5

We are planning to give HTTP/3 a new icon, then publish new version to Chrome Web Store.

By the way, since HTTP/3 has not been widely used, there seems no different between v0.0.3 and v0.0.4 currently.

**Comment by whalehub** [comment]
Thanks for the explanation, I'll wait for the new version to be published.

**Comment by pd4d10** [comment]
Hi, @whalehub , the v0.0.4 version has been published.

**Comment by whalehub** [comment]
@pd4d10 Thanks!
